### ISSUE TITLE
[BE] HTTP 요청 메서드가 아닌 요청은 로깅하지 않도록 한다

### ISSUE THREAD

**Issue by 70825** [woowacourse-teams/2023-fun-eat#654]
## 버그가 발생한 곳

- #626 을 적용하니 이상한 로그들이 보였습니다. 확인해보니 핸드쉐이킹 요청이 0x160으로 시작하는데,  요청 메서드로 파싱할 때 에러가 나오고, 0x030...도  에러가 나옵니다.
- 참고 자료 : https://www.cisco.com/c/ko_kr/support/docs/security-vpn/secure-socket-layer-ssl/116181-technote-product-00.html

## 버그 상황 재연

그라파나 로그 확인해보면 이게 보입니다.

<img width="1343" alt="스크린샷 2023-09-16 오후 5 02 57" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/79046106/abc6e4fa-5454-4fd6-a797-39e7226c7957">

<img width="1344" alt="스크린샷 2023-09-16 오후 5 03 03" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/79046106/893a740d-93b7-44df-a4b5-012ca28d0e4a">

## 현재 동작

- 모든 HTTP 요청에 대해 로깅을 하고 있습니다.

## 기대 동작

- HTTP 요청 메서드만 로깅을 할 수 있도록 합니다.
- HTTP 요청 메서드 - https://developer.mozilla.org/ko/docs/Web/HTTP/Methods

**Comment by 70825** [comment]
AOP 로깅으로 인해 발생하는 문제가 아니였으므로 이슈 닫음

```
[INFO ] [2023-09-01 11:36:02:74885956] [http-nio-8080-exec-6] [org.apache.coyote.http11.Http11Processor:175] - Error parsing HTTP request header |  
  |   | at java.base/java.lang.Thread.run(Thread.java:829) |  
  |   | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) |  
  |   | at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) |  
  |   | at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) |  
  |   | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) |  
  |   | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) |  
  |   | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) |  
  |   | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) |  
  |   | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263) |  
  |   | at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407) |  
  |   | java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x00{0x010x000x00w0x030x03C0xcct0xc70xbd0xf90xf2J0x06hf0x15Nz0x130x020xe3[0xbfD0x9e0xfa0x00i0xfd0x060x8a0x820xc7#B0x1e0x000x000x1a0xc0/0xc0+0xc00x110xc00x070xc00x130xc00x090xc00x140xc00x0a0x000x050x00/0x0050xc00x120x000x0a0x010x000x0040x000x050x000x050x010x000x000x000x000x000x0a0x000x080x000x060x000x170x000x180x000x190x000x0b0x000x020x010x000x000x0d0x000x100x000x0e0x040x010x040x030x020x010x020x030x040x010x050x010x060x010xff0x010x000x010x00...]. HTTP method names must be tokens |  
  |   | Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level. |  
  |   | [INFO ] [2023-09-01 01:56:08:40091353] [http-nio-8080-exec-2] [org.apache.coyote.http11.Http11Processor:175] - Error parsing HTTP request header |  
  |   |  
```

**Comment by 70825** [comment]
톰캣 코드 확인해보니 아래 과정을 통해 Http Method를 가져옵니다.

### 1. org.apache.catalina.Request.java

https://github.com/apache/tomcat/blob/main/java/org/apache/catalina/connector/Request.java#L2187-L2189

```java
    @Override
    public String getMethod() {
        return coyoteRequest.method().toString();
    }
```



### 2. org.apache.coyote.Requeset.java

https://github.com/apache/tomcat/blob/main/java/org/apache/coyote/Request.java#L311-L313

```java
    private final MessageBytes methodMB = MessageBytes.newInstance();

    public MessageBytes method() {
        return methodMB;
    }
```

### 3. org.apache.tomcat.util.buf.MessageBytes

https://github.com/apache/tomcat/blob/main/java/org/apache/tomcat/util/buf/MessageBytes.java


### 4. org.apache.coyote.http11.Http11InputBuffer (적절하게 파싱해서 MessageBytes로 설정해주는 역할)

https://github.com/apache/tomcat/blob/main/java/org/apache/coyote/http11/Http11InputBuffer.java#L378-L407

```java
        if (parsingRequestLinePhase == 2) {
            //
            // Reading the method name
            // Method name is a token
            //
            boolean space = false;
            while (!space) {
                // Read new bytes if needed
                if (byteBuffer.position() >= byteBuffer.limit()) {
                    if (!fill(false)) {
                        return false;
                    }
                }
                // Spec says method name is a token followed by a single SP but
                // also be tolerant of multiple SP and/or HT.
                int pos = byteBuffer.position();
                chr = byteBuffer.get();
                if (chr == Constants.SP || chr == Constants.HT) {
                    space = true;
                    request.method().setBytes(byteBuffer.array(), parsingRequestLineStart,
                            pos - parsingRequestLineStart);
                } else if (!HttpParser.isToken(chr)) {
                    // Avoid unknown protocol triggering an additional error
                    request.protocol().setString(Constants.HTTP_11);
                    String invalidMethodValue = parseInvalid(parsingRequestLineStart, byteBuffer);
                    throw new IllegalArgumentException(sm.getString("iib.invalidmethod", invalidMethodValue));
                }
            }
            parsingRequestLinePhase = 3;
        }
```

절차지향적이라 코드 확인하기 좋습니다
